CREATE DATABASE QuanLyDiemThi;
USE QuanLyDiemThi;
CREATE TABLE HocSinh (
	MaHS VARCHAR (20) PRIMARY KEY,
    TenHS VARCHAR (45),
    NgaySinh DATETIME,
    Lop VARCHAR (20),
    GT VARCHAR (20)
);

CREATE TABLE MonHoc (
	MaMH VARCHAR (20) PRIMARY KEY,
    TenMH VARCHAR (45)
);

CREATE TABLE BangDiem (
	MaHS VARCHAR (20),
    MaMH VARCHAR (20),
    DiemThi INT,
    NgayKT DATETIME,
    PRIMARY KEY (MaHS, MaMH),
    FOREIGN KEY (MaHS) REFERENCES HocSinh (MaHS)
);

CREATE TABLE GiaoVien (
	MaGV VARCHAR (20) PRIMARY KEY,
    TenGV VARCHAR (20),
    SDT VARCHAR (20)
);

ALTER TABLE MonHoc ADD MaGV VARCHAR (20);
ALTER TABLE MoNhOC ADD CONSTRAINT FK_MaGV FOREIGN KEY (MaGV) REFERENCES GiaoVien (MaGV);